---
version: '3.9'
services:
  pyroscope:
    image: grafana/pyroscope
    ports:
      - '4040:4040'
    
  cpp-resource-consuming:
    build: ./cpp_app
    ports:
      - '8080:8080'
  
  java-resource-consuming:
    build: ./java_app

  grafana-agent:
    image: 'grafana/agent:main'
    user: root
    privileged: true
    pid: 'host'
    environment:
      - AGENT_MODE=flow
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./agent.river:/agent.river
    ports:
      - '12345:12345'
    command:
      - 'run'
      - './agent.river'
      - '--storage.path=/tmp/agent'
      - '--server.http.listen-addr=0.0.0.0:12345'
